# Site settings
title: "Marco's Personal Site"
email: marco.selvi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website.
  It contains information about me, what I do, the projects that I have running and how to reach me.
  It also contains random curiosities.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcoselvi.github.io" # the base hostname & protocol for your site
twitter_username: macselvi
github_username:  marcoselvi
facebook_username: Shogun42
linkedin_username: marcoselvi

timezone: Europe/London


# Build settings
markdown: kramdown
permalink: pretty

port: 4000
